#!/usr/bin/env python3
"""生成 M1 对拍 fixtures（ts/fixtures/）。可重复运行（幂等覆盖）。"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIX = os.path.join(ROOT, "ts", "fixtures")
PROJ = os.path.join(FIX, "projects", "-w-projA")
ARCH = os.path.join(FIX, "archive", "-w-projA")
os.makedirs(PROJ, exist_ok=True)
os.makedirs(ARCH, exist_ok=True)


def w(name, objs):
    with open(os.path.join(PROJ, name), "w", encoding="utf-8") as f:
        for o in objs:
            f.write(json.dumps(o, ensure_ascii=False) + "\n")


def user(sid, cwd, text, sidechain=False, ts="2026-09-01T00:00:00Z"):
    o = {"type": "user", "sessionId": sid, "cwd": cwd, "timestamp": ts,
         "gitBranch": "master", "message": {"role": "user", "content": text}}
    if sidechain:
        o["isSidechain"] = True
    return o


def asst(sid, text):
    return {"type": "assistant", "sessionId": sid, "cwd": "/w/projA",
            "timestamp": "2026-09-01T00:01:00Z",
            "message": {"role": "assistant", "content": [{"type": "text", "text": text}]}}


# 1 正常会话
w("normal.jsonl", [user("sid-n", "/w/projA", "修复登录bug"), asst("sid-n", "已修复")])

# 2 内部前缀 ×6：全部被跳过，真实首问是最后一条
w("internal.jsonl", [
    user("sid-int", "/w/projA", "Below is a conversation log from a Claude Code session.\n忽略"),
    user("sid-int", "/w/projA", "Caveat: The messages below were generated by the user when running `claude --resume`.\n忽略"),
    user("sid-int", "/w/projA", "<local-command-续> 忽略"),
    user("sid-int", "/w/projA", "<command-name>/clear</command-name>"),
    user("sid-int", "/w/projA", "<command-message>忽略"),
    user("sid-int", "/w/projA", "<command-args>忽略"),
    user("sid-int", "/w/projA", "This session is being continued from a previous conversation"),
    user("sid-int", "/w/projA", "真正的第一个问题"),
])

# 3 sidechain 折叠
w("sidedef.jsonl", [
    user("sid-side", "/w/projA", "侧链问题不应成为首问", sidechain=True),
    user("sid-side", "/w/projA", "真实首问"),
])

# 4 infile summary：leafUuid 行 + 真实会话
w("infile-summary.jsonl", [
    {"type": "summary", "summary": "续会话标题", "leafUuid": "prev-1"},
    user("sid-inf", "/w/projA", "第一问"),
    {"type": "user", "sessionId": "sid-inf", "message": None},
    asst("sid-inf", "hi"),
])

# 5 sidecar-only：单行 summary → Sidecar 对象（scan 时折叠，不出现在 metas）
with open(os.path.join(PROJ, "sidecar-only.jsonl"), "w", encoding="utf-8") as f:
    f.write(json.dumps({"type": "summary", "summary": "孤立摘要", "leafUuid": "sid-nothing"}) + "\n")

# 6 ai-title append-only：后写赢
w("ai-title.jsonl", [
    {"type": "mode"},
    {"type": "ai-title", "aiTitle": "旧标题"},
    {"type": "ai-title", "aiTitle": "新标题赢"},
    user("sid-ai", "/w/projA", "问"),
])

# 7 custom-title：最高优先
w("custom-title.jsonl", [
    {"type": "custom-title", "customTitle": "官方改名", "sessionId": "sid-ct"},
    user("sid-ct", "/w/projA", "首问"),
])

# 8 custom + ai 并存 → custom 赢
w("custom-ai.jsonl", [
    {"type": "ai-title", "aiTitle": "AI 标题"},
    {"type": "custom-title", "customTitle": "人改标题"},
    user("sid-ca", "/w/projA", "首问"),
])

# 9 坏行 + 无有效消息 → title=文件名
w("badline.jsonl", ["not json\n"] * 3 + [{"type": "mode"}])

# 10 message 为 null 的 user 行不崩
w("nullmsg.jsonl", [
    user("sid-null", "/w/projA", "真实首问"),
    {"type": "user", "sessionId": "sid-null", "message": None},
    asst("sid-null", "hi"),
])

# 11 多行首问 → 标题净化为单行
w("multiline.jsonl", [user("sid-multi", "/w/projA", "第一行\n\n第二行 内容")])

# 12 无 sessionId
w("nosid.jsonl", [{"type": "user", "cwd": "/w/projA",
                   "message": {"role": "user", "content": "没有sessionId的首问"}}])

# 13 sdk-cli 衍生会话（scan 层过滤；parse 层 entrypoint 记录）
w("sdk-cli.jsonl", [
    {"type": "user", "sessionId": "sid-sdk", "cwd": "/w/projA", "entrypoint": "sdk-cli",
     "message": {"role": "user", "content": "SDK 衍生会话"}},
])

# 14 首问在 64KB 采样窗外：头部样板 >64KB，真实首问在尾部
pad = "Caveat: The messages below were generated by the user when running `claude --resume`.\n"
w("bigfile.jsonl", [user("sid-big", "/w/projA", pad * 900),
                    user("sid-big", "/w/projA", "采样窗外的真实首问"),
                    asst("sid-big", "答复")])

# 15 last_reply 超 4000 截断
w("longreply.jsonl", [user("sid-lr", "/w/projA", "问"),
                      asst("sid-lr", "很长的回复" * 900)])

# 16 归档样例
with open(os.path.join(ARCH, "arch1.jsonl"), "w", encoding="utf-8") as f:
    f.write(json.dumps(user("sid-arch", "/w/projA", "归档会话")) + "\n")

# launch_dir 用例表（两侧共享；树由 dump_py/parity 各自幂等创建）
cases = {
    "real-hyphen-dir": {"encoded": "-Users-biedongbin-workspace-ai-robot-coding", "hint": ""},
    "real-underscore": {"encoded": "-Users-biedongbin-workspace-biedb-tmp-claude-session", "hint": ""},
    "hint-disambiguate": {"encoded": "-tmp-ccs-parity-ld-my-project-x",
                          "hint": "/tmp/ccs_parity_ld/my-project-x"},
    "deleted-dir-join-all": {"encoded": "-Users-biedongbin-nonexistent-abc-def", "hint": ""},
    "no-leader-dash": {"encoded": "w-projA", "hint": ""},
    "empty-parts": {"encoded": "-", "hint": ""},
}
with open(os.path.join(FIX, "launchdir_cases.json"), "w", encoding="utf-8") as f:
    json.dump(cases, f, ensure_ascii=False, indent=2)

print("fixtures ok:", PROJ)
